### ISSUE TITLE
Secret_Key in Setting.py

### ISSUE THREAD

**Issue by laminfaty** [cfpb/mapusaurus#295]
Let's make sure that the secret_key under mapusaurus/mapusaurus/settings/settings.py is not being used production. If it is, let's be certain that it is taken out.

**Comment by cmc333333** [comment]
I've found that including a "default" setting can make getting up and running easy, but throw red flags like Lamin's. As a result, I've switched to the default key being randomly generated at django startup. This will break sessions between reboot, but that's generally not a problem for local development/tests.

See https://github.com/18F/peacecorps-site/blob/master/peacecorps/peacecorps/settings/test.py#L3-5 for an example.

**Comment by virtix** [comment]
Noting that the key being used is development-safe would alleviate doubts. For example, if the secret_key were predictable for a given environment, then this could included in a comment, too. If it differs, then you would know something's amiss. 

```python

# If in a non-production environment, this key should be '($2ob)%vv$wv7jl-$e!=#z!+bhihs@o%$+@c0yqrz&8*f@#hhi'
SECRET_KEY =  gen_secretkey(56)

...

_STATIC_SECRET_KEY = '($2ob)%vv$wv7jl-$e!=#z!+bhihs@o%$+@c0yqrz&8*f@#hhi'

def gen_secretkey (len):
  if is_production():
    return get_random_string(len)
  
  return _STATIC_SECRET_KEY
   

def is_production():
  ...

```
Then again, perhaps, development managers should stay out the weeds :grin:

**Comment by mehtadev17** [comment]
Allowed developer to use their own security key in settings.py. Overriding the key in local_settings.py for production environment.
